language: generic
sudo: required

services:
  - docker

before_install:
    - docker build -t shariqm/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true shariqm/react-test npm test


    after_success:
    - docker build -t shariqm/multi-client ./client
    - docker build -t shariqm/multi-nginx ./nginx
    - docker build -t shariqm/multi-server ./server
    - docker build -t shariqm/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push those to docker hub
    - docker push shariqm/multi-client
    - docker push shariqm/multi-nginx
    - docker push shariqm/multi-server
    - docker push shariqm/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-145169095479
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
    
